In [1]:
from numpy import array
sample_Tensor = array([
  [[1,4,7],      [2,5,8],      [3,6,9]],
  [[10,40,70],   [20,50,80],   [30,60,90]],
  [[100,400,700],[200,500,800],[300,600,900]],
  ])
print("The Shape of the Tensor is : ",sample_Tensor.shape)
print("\nThe Tensor is: \n",sample_Tensor)

The Shape of the Tensor is :  (3, 3, 3)

The Tensor is: 
 [[[  1   4   7]
  [  2   5   8]
  [  3   6   9]]

 [[ 10  40  70]
  [ 20  50  80]
  [ 30  60  90]]

 [[100 400 700]
  [200 500 800]
  [300 600 900]]]


In [2]:
import torch
import numpy

temp_tensor = torch.tensor([7.82,7.1,6.9,9.4,1.53])
print("The Tensor is : ",temp_tensor)
 
temp_tensor_2_array = temp_tensor.numpy()
print("Conversion Successful!!\n")

print("The Converted array is : ",temp_tensor_2_array)

The Tensor is :  tensor([7.8200, 7.1000, 6.9000, 9.4000, 1.5300])
Conversion Successful!!

The Converted array is :  [7.82 7.1  6.9  9.4  1.53]


In [3]:
import torch
import numpy

temp_tensor = torch.tensor([[7.82,7.1,6.9,9.4,1.53],
                           [8.2,8.3,2.4,9.4,2.3]])
print("The Tensor is : ",temp_tensor)
 
temp_tensor_2_array = temp_tensor.numpy()
print("Conversion Successful!!\n")

print("The Converted array is : ",temp_tensor_2_array)

The Tensor is :  tensor([[7.8200, 7.1000, 6.9000, 9.4000, 1.5300],
        [8.2000, 8.3000, 2.4000, 9.4000, 2.3000]])
Conversion Successful!!

The Converted array is :  [[7.82 7.1  6.9  9.4  1.53]
 [8.2  8.3  2.4  9.4  2.3 ]]


In [4]:
import tensorflow as tf
 
values = tf.constant([[400,132],[763,8724]])                 
tensor = tf.add(values, 1)
print("The tensor is : ",values)
print("\nThe array is : ",values.numpy())

The tensor is :  tf.Tensor(
[[ 400  132]
 [ 763 8724]], shape=(2, 2), dtype=int32)

The array is :  [[ 400  132]
 [ 763 8724]]
